apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs-basic
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://125.212.203.156:31235"
  clusterid: "45ac138fa13aeb0c41f2760fbcc0b350"
  restuser: "admin"
  secretNamespace: "default"
  secretName: "heketi-secret"
  volumetype: "replicate:1"
allowVolumeExpansion: true
